CUDNN_BENCHMARK: True
DATALOADER: {NAIVE_WAY: True, NUM_INSTANCE: 4, NUM_WORKERS: 8, PK_SAMPLER: True}
DATASETS:
  COMBINEALL: True
  NAMES: [CUHK03, SAIVT, AirportALERT, iLIDS, PKU, PRAI, SenseReID, SYSU_mm, Thermalworld,
    PeS3D, CAVIARa, VIPeR, Shinpuhkan, WildTrackCrop, cuhkSYSU, LPW]
  TESTS: [DukeMTMC, MSMT17, Market1501]
INPUT:
  AUTOAUG_PROB: 0.1
  CJ: {BRIGHTNESS: 0.15, CONTRAST: 0.1, ENABLED: True, HUE: 0.0, PROB: 0.5, SATURATION: 0.0}
  DO_AUGMIX: False
  DO_AUTOAUG: True
  DO_FLIP: True
  DO_PAD: True
  FLIP_PROB: 0.5
  PADDING: 10
  PADDING_MODE: constant
  REA:
    ENABLED: True
    PROB: 0.5
    VALUE: [151.98, 142.29000000000002, 126.735]
  RPT: {ENABLED: False, PROB: 0.5}
  SIZE_TEST: [256, 128]
  SIZE_TRAIN: [256, 128]
KD: {MODEL_CONFIG: test_person_search/teacher_source_config.yaml, MODEL_WEIGHTS: /export/wei.zhang/pretrained/teachers/source/model_best.pth}
MODEL:
  BACKBONE: {DEPTH: 50x, FEAT_DIM: 2048, LAST_STRIDE: 1, NAME: build_resnet_backbone_distill,
    NORM: BN, PRETRAIN: True, PRETRAIN_PATH: '', WITH_IBN: True, WITH_NL: False, WITH_SE: False}
  DEVICE: cuda
  FREEZE_LAYERS: [backbone]
  HEADS: {CLS_LAYER: circleSoftmax, EMBEDDING_DIM: 0, MARGIN: 0.35, NAME: EmbeddingHead,
    NECK_FEAT: after, NORM: syncBN, NUM_CLASSES: 31423, POOL_LAYER: gempool, SCALE: 64,
    WITH_BNNECK: True}
  LOSSES:
    CE: {ALPHA: 0.2, EPSILON: 0.0, SCALE: 1.0}
    CIRCLE: {GAMMA: 128, MARGIN: 0.25, SCALE: 1.0}
    COSFACE: {GAMMA: 128, MARGIN: 0.25, SCALE: 1.0}
    FL: {ALPHA: 0.25, GAMMA: 2, SCALE: 1.0}
    NAME: [CrossEntropyLoss]
    TRI: {HARD_MINING: True, MARGIN: 0.3, NORM_FEAT: False, SCALE: 1.0}
  META_ARCHITECTURE: Distiller
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.120000000000005, 57.375]
  QUEUE_SIZE: 8192
  WEIGHTS: /export/wei.zhang/pretrained/teachers/source/model_best.pth
OUTPUT_DIR: projects/bjzProject/psd_log/alldomain_r50ibn_0001
SOLVER:
  BASE_LR: 0.04
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 3
  DELAY_EPOCHS: 0
  ETA_MIN_LR: 4.0e-05
  FP16_ENABLED: False
  FREEZE_FC_ITERS: 0
  FREEZE_ITERS: 2500
  GAMMA: 0.1
  HEADS_LR_FACTOR: 1.0
  IMS_PER_BATCH: 256
  MAX_EPOCH: 30
  MOMENTUM: 0.9
  NESTEROV: True
  OPT: SGD
  SCHED: CosineAnnealingLR
  STEPS: [30, 55]
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 5000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
TEST:
  AQE: {ALPHA: 3.0, ENABLED: False, QE_K: 5, QE_TIME: 1}
  EVAL_PERIOD: 3
  FLIP_ENABLED: False
  IMS_PER_BATCH: 512
  METRIC: cosine
  PRECISE_BN: {DATASET: Market1501, ENABLED: False, NUM_ITER: 300}
  RERANK: {ENABLED: False, K1: 20, K2: 6, LAMBDA: 0.3}
  ROC_ENABLED: False

